[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/pix"
  to = "/.netlify/functions/pix"
  status = 200

[[redirects]]
  from = "/netlify/functions/pix.js"
  to = "/.netlify/functions/pix"
  status = 200

[[headers]]
  for = "/netlify/*"
  [headers.values]
    X-Robots-Tag = "noindex"
